support for swift 3
ochococo/OOD-Principles-In-Swift pull request #8
Opened 2016-11-21 19:44 UTC by JackieQi

Tried to convert sample code to swift 3.

2016-11-21 20:05 UTC, ochococo requested changes
Thanks for contributing <3 

Some issues were found.

2016-11-21 20:05 UTC, ochococo commented on OOD-Principles-In-Swift.playground/contents.swift
> +    func landOn(_ on: LandingSiteHaving) -> String
`land(on: LandingSiteHaving`

2016-11-21 20:05 UTC, ochococo commented on OOD-Principles-In-Swift.playground/contents.swift
> +    func travelInTime(_ time: TimeInterval) -> String
`travel(time: TimeInterval)` ?

2016-11-21 20:05 UTC, ochococo commented on README.md
> -⚠️ See my most popular project to date: [Design-Patterns-In-Swift](https://github.com/ochococo/Design-Patterns-In-Swift)
😋 Okaaaay 😋

2016-11-21 20:05 UTC, ochococo commented on README.md
> +func willReturnObjectOrError(from URL: URL) -> (object: Any?, error: NSError?) {
`(from url: URL)`?

2016-11-21 20:21 UTC, JackieQi commented on README.md
> -⚠️ See my most popular project to date: [Design-Patterns-In-Swift](https://github.com/ochococo/Design-Patterns-In-Swift)
Didn't mean to do that. sorry.

2016-11-21 20:22 UTC, JackieQi commented on README.md
> +func willReturnObjectOrError(from URL: URL) -> (object: Any?, error: NSError?) {
URLRequest doesn't take optional URL. so add let check in new commit

2016-11-21 20:23 UTC, JackieQi commented on OOD-Principles-In-Swift.playground/contents.swift
> +    func travelInTime(_ time: TimeInterval) -> String
I add `in` in parameter which is more consistent with old API i think.

2017-03-28 09:47 UTC, naeemshaikh90 commented
@ochococo Whats the current status for this? Are you going to merge this PR?

2019-04-15 12:00 UTC, ochococo commented
outdated

2019-04-15 12:00 UTC, closed without merging